modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="ironnest"
version="0.1.0"
displayName="Iron Nest: Artillery"
description='''Тяжёлая артиллерия по мотивам Iron Nest.'''

[[dependencies.ironnest]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.ironnest]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
